-- Base estructural obtenida de SQLGUTPATATE. PostgreSQL 15+.
-- No incluye datos operativos, vistas, funciones ni procedimientos.
-- Preserva nombres exactos: usar identificadores entre comillas en las consultas.
-- Pendiente paridad de collation y precision temporal (SQL Server: 7, PostgreSQL: 6).
CREATE SCHEMA IF NOT EXISTS "dbo";

CREATE TABLE "dbo"."ActivacionBancaLinea" (
  "ActivacionId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "SocioId" bigint NOT NULL,
  "PIN" varchar(4) NOT NULL,
  "CodigoVerificacion" varchar(10) NOT NULL,
  "FechaRegistro" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "AceptoDatosPersonales" boolean DEFAULT false NOT NULL,
  "FechaAceptacionDatos" timestamp(0) without time zone,
  "Activo" boolean DEFAULT false NOT NULL
);

CREATE TABLE "dbo"."AgenteEngrams" (
  "EngramId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "Clave" varchar(100) NOT NULL,
  "Modulo" varchar(50) NOT NULL,
  "Contenido" text NOT NULL,
  "FechaActualizacion" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "UsuarioModificacion" varchar(50)
);

CREATE TABLE "dbo"."AsientosContablesDPF" (
  "AsientoID" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "DepositoID" varchar(20) NOT NULL,
  "TipoOperacion" varchar(30) NOT NULL,
  "CuentaContable" varchar(15) NOT NULL,
  "NombreCuenta" varchar(120) NOT NULL,
  "DebeAmount" numeric(15,2) DEFAULT ((0.00)) NOT NULL,
  "HaberAmount" numeric(15,2) DEFAULT ((0.00)) NOT NULL,
  "Concepto" varchar(300) NOT NULL,
  "FechaAsiento" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "UsuarioID" varchar(50) NOT NULL
);

CREATE TABLE "dbo"."AuditoriaProcesos" (
  "AuditoriaId" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "Proceso" varchar(50) NOT NULL,
  "Accion" varchar(50) NOT NULL,
  "EntidadTipo" varchar(50) NOT NULL,
  "EntidadId" varchar(50),
  "UsuarioId" varchar(20) NOT NULL,
  "CampoAfectado" varchar(100),
  "ValorAnterior" text,
  "ValorNuevo" text,
  "Detalle" varchar(500),
  "IPOrigen" varchar(45),
  "FechaRegistro" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE "dbo"."AuditoriaUsuarios" (
  "AuditoriaId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "UsuarioId" varchar(20) NOT NULL,
  "Concepto" varchar(100) NOT NULL,
  "Detalle" varchar(500) NOT NULL,
  "FechaRegistro" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE "dbo"."ClientesInformix" (
  "ClienteInformixId" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "OrigenSistema" varchar(30) NOT NULL,
  "OrigenClienteId" integer NOT NULL,
  "CodigoTipoCliente" integer,
  "NumeroCliente" integer,
  "CodigoOficina" integer,
  "CodigoTipoIdentificacion" char(1),
  "Identificacion" varchar(13),
  "Apellidos" varchar(60),
  "Nombres" varchar(30),
  "NombreCompleto" varchar(120) NOT NULL,
  "FechaNacimiento" date,
  "CodigoSector" integer,
  "DireccionDomicilio" varchar(55),
  "FechaUltimaActualizacion" timestamp(0) without time zone,
  "FechaIngreso" timestamp(0) without time zone,
  "FechaSalida" date,
  "Email" varchar(80),
  "NaturalezaJuridica" smallint,
  "EstadoCliente" smallint,
  "CodigoCalificacion" integer,
  "RepresentanteLegal" varchar(50),
  "IdentificacionRepresentante" varchar(13),
  "TipoIdentificacionRepresentante" char(1),
  "CodigoPais" integer,
  "CodigoUsuario" integer,
  "CodigoOficinaTrabajo" integer,
  "ReferenciaDireccion" varchar(100),
  "CodigoCocu" integer,
  "EstadoAdicional" smallint,
  "CodigoDiscapacidad" smallint,
  "CodigoTipoVivienda" integer,
  "ValorVivienda" numeric(15,2),
  "NumeroCargas" smallint,
  "CodigoTipoCargaSocio" integer,
  "CodigoAuid" integer,
  "FechaAsamblea" date,
  "CodigoProfesion" integer,
  "BanderaPeps" smallint,
  "CodigoTipoVinculacion" integer,
  "BanderaGrupo" smallint,
  "CodigoGrupo" integer,
  "CodigoTipoResidencia" integer,
  "PaisResidencia" integer,
  "BanderaPdpe" smallint,
  "HuellaDactilar" varchar(10),
  "FechaCreacion" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "FechaActualizacion" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE "dbo"."ControlCaja" (
  "ControlId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "UsuarioId" varchar(50) NOT NULL,
  "Fecha" date NOT NULL,
  "HoraApertura" timestamp(0) without time zone NOT NULL,
  "HoraCierre" timestamp(0) without time zone,
  "SaldoApertura" numeric(18,2) NOT NULL,
  "SaldoCierre" numeric(18,2),
  "Estado" varchar(20) NOT NULL
);

CREATE TABLE "dbo"."Creditos" (
  "CreditoID" varchar(50) NOT NULL,
  "SolicitudID" varchar(50) NOT NULL,
  "SocioID" bigint NOT NULL,
  "Monto" numeric(15,2) NOT NULL,
  "Saldo" numeric(15,2) NOT NULL,
  "Tasa" numeric(5,2) NOT NULL,
  "Plazo" integer NOT NULL,
  "Tipo" varchar(100) NOT NULL,
  "Estado" varchar(30) NOT NULL,
  "FechaDesembolso" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "FechaVencimiento" varchar(50),
  "TipoAprobacion" varchar(50),
  "ActaSesion" varchar(100),
  "TipoPrenda" varchar(100),
  "AvaluoPrendario" numeric(15,2),
  "ObservacionTecnicaPrenda" varchar(500),
  "ValorCobertura" numeric(10,2)
);

CREATE TABLE "dbo"."CuentasAhorro" (
  "CuentaId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "SocioId" bigint NOT NULL,
  "NumeroCuenta" varchar(20) NOT NULL,
  "CodigoProducto" integer NOT NULL,
  "Saldo" numeric(18,2) DEFAULT ((0.00)) NOT NULL,
  "FechaApertura" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "Estado" varchar(20) DEFAULT ('ACTIVA') NOT NULL
);

CREATE TABLE "dbo"."Denominaciones" (
  "CodigoDenominacion" varchar(10) NOT NULL,
  "Valor" numeric(5,2) NOT NULL,
  "Tipo" varchar(10) NOT NULL,
  "Descripcion" varchar(50) NOT NULL
);

CREATE TABLE "dbo"."DepositosPlazo" (
  "DepositoID" varchar(20) NOT NULL,
  "SOCIOID" bigint NOT NULL,
  "Identificacion" varchar(20) NOT NULL,
  "NombreSocio" varchar(200) NOT NULL,
  "NumCertificado" varchar(20) NOT NULL,
  "TasaID" integer NOT NULL,
  "TasaNominalAnual" numeric(5,2) NOT NULL,
  "PlazosDias" integer NOT NULL,
  "MontoCapital" numeric(15,2) NOT NULL,
  "InteresProyectado" numeric(15,2) NOT NULL,
  "RetencionProyectada" numeric(15,2) NOT NULL,
  "InteresNetoProyectado" numeric(15,2) NOT NULL,
  "FechaApertura" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "FechaVencimiento" timestamp(0) without time zone NOT NULL,
  "Estado" varchar(20) DEFAULT ('ACTIVO') NOT NULL,
  "TipoRenovacion" varchar(20) DEFAULT ('NO_RENOVAR') NOT NULL,
  "ModalidadPago" varchar(20) DEFAULT ('AL_VENCIMIENTO') NOT NULL,
  "CuentaAhorrosRelacionada" varchar(20),
  "CuentaContableDPF" varchar(10) NOT NULL,
  "FechaLiquidacion" timestamp(0) without time zone,
  "InteresLiquidado" numeric(15,2),
  "RetencionAplicada" numeric(15,2),
  "InteresNetoLiquidado" numeric(15,2),
  "PenalizacionAplicada" numeric(15,2),
  "MotivosCancelacion" varchar(400),
  "NumeroRenovacion" integer DEFAULT ((0)) NOT NULL,
  "DepositoOrigenID" varchar(20),
  "UsuarioAperturaID" varchar(50) NOT NULL,
  "UsuarioLiquidacionID" varchar(50),
  "Observaciones" varchar(500),
  "FechaCreacion" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "FechaModificacion" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE "dbo"."DetalleEfectivoTransaccion" (
  "DetalleId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "AsientoId" integer NOT NULL,
  "CodigoDenominacion" varchar(10) NOT NULL,
  "Cantidad" integer NOT NULL,
  "Total" numeric(18,2) NOT NULL
);

CREATE TABLE "dbo"."HomologacionPerfilInformix" (
  "CodigoPerfil" char(2) NOT NULL,
  "RolApp" varchar(30) NOT NULL,
  "Descripcion" varchar(150),
  "Activo" boolean DEFAULT true NOT NULL
);

CREATE TABLE "dbo"."MigracionesAplicadas" (
  "MigracionId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "Archivo" varchar(200) NOT NULL,
  "HashContenido" varchar(64) NOT NULL,
  "FechaAplicada" timestamp(6) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "AplicadaPor" varchar(100),
  "DuracionMs" integer,
  "Notas" varchar(500)
);

CREATE TABLE "dbo"."ParametrosPatrimonioTecnico" (
  "ParametroId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "Componente" varchar(20) NOT NULL,
  "PrefijoCuenta" varchar(15) NOT NULL,
  "Factor" numeric(5,4) DEFAULT ((1)) NOT NULL,
  "SaldoComo" varchar(10) DEFAULT ('ACREEDOR') NOT NULL,
  "LimitePctAPR" numeric(7,4),
  "Descripcion" varchar(200),
  "BaseNormativa" varchar(200),
  "Activo" boolean DEFAULT true NOT NULL
);

CREATE TABLE "dbo"."parametrosproductos" (
  "ProductoId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "CodigoProducto" integer NOT NULL,
  "Nombre" varchar(100) NOT NULL,
  "TipoDeposito" varchar(100) NOT NULL,
  "EsCertificado" boolean DEFAULT false NOT NULL,
  "CuentaActiva" varchar(20) NOT NULL,
  "CuentaInactiva" varchar(20) NOT NULL,
  "CuentaGasto" varchar(20),
  "CuentaProvision" varchar(20),
  "CuentaDepositosConfirmar" varchar(20),
  "NumCtas4Dig" integer DEFAULT ((28)) NOT NULL,
  "PermiteDepositos" boolean DEFAULT true NOT NULL,
  "PermiteRetiros" boolean DEFAULT true NOT NULL,
  "PermiteDebitos" boolean DEFAULT true NOT NULL,
  "PermiteCreditos" boolean DEFAULT true NOT NULL,
  "PermiteTransferencias" boolean DEFAULT true NOT NULL,
  "Tasa" varchar(50) DEFAULT ('TASA NOMINAL') NOT NULL,
  "FormaPago" varchar(100) DEFAULT ('MOVIMIENTO HISTORICO PONDERADO BASE') NOT NULL,
  "MesesAcreditacion" varchar(100) DEFAULT ('Diciembre') NOT NULL
);

CREATE TABLE "dbo"."ParametrosProvisionCartera" (
  "ParametroId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "Segmento" varchar(20) NOT NULL,
  "Calificacion" varchar(5) NOT NULL,
  "DiasMoraDesde" integer NOT NULL,
  "DiasMoraHasta" integer,
  "PorcentajeProvision" numeric(7,4) NOT NULL,
  "CuentaProvision" varchar(20) NOT NULL,
  "BaseNormativa" varchar(200),
  "Activo" boolean DEFAULT true NOT NULL
);

CREATE TABLE "dbo"."ParametrosRegulatorios" (
  "Clave" varchar(60) NOT NULL,
  "Valor" numeric(18,6) NOT NULL,
  "Unidad" varchar(20),
  "Descripcion" varchar(300),
  "BaseNormativa" varchar(200)
);

CREATE TABLE "dbo"."PlanCuentas" (
  "CuentaContableId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "Codigo" varchar(15) NOT NULL,
  "Nombre" varchar(200) NOT NULL,
  "TipoCuenta" varchar(20) NOT NULL,
  "EsAgrupador" boolean DEFAULT false NOT NULL,
  "Nivel" integer GENERATED ALWAYS AS (length(rtrim("Codigo"))) STORED,
  "FechaCreacion" timestamp(6) without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE "dbo"."PonderacionesRiesgo" (
  "PonderacionId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "PrefijoCuenta" varchar(15) NOT NULL,
  "Ponderacion" numeric(5,4) NOT NULL,
  "Categoria" varchar(60) NOT NULL,
  "Descripcion" varchar(200),
  "BaseNormativa" varchar(200),
  "Activo" boolean DEFAULT true NOT NULL
);

CREATE TABLE "dbo"."ReclasificacionCartera" (
  "ProcesoId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "FechaCorte" date NOT NULL,
  "Estado" varchar(20) NOT NULL,
  "UsuarioId" varchar(50) NOT NULL,
  "FechaEjecucion" timestamp(6) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "OperacionesEvaluadas" integer DEFAULT ((0)) NOT NULL,
  "MontoReclasificado" numeric(15,2) DEFAULT ((0)) NOT NULL,
  "CarteraBruta" numeric(15,2) DEFAULT ((0)) NOT NULL,
  "CarteraImproductiva" numeric(15,2) DEFAULT ((0)) NOT NULL,
  "ProvisionRequerida" numeric(15,2) DEFAULT ((0)) NOT NULL,
  "ProvisionConstituida" numeric(15,2) DEFAULT ((0)) NOT NULL,
  "AsientoProvisionado" numeric(15,2) DEFAULT ((0)) NOT NULL,
  "ReversaDeProcesoId" integer,
  "Observaciones" varchar(500)
);

CREATE TABLE "dbo"."ReclasificacionCarteraDetalle" (
  "DetalleId" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "ProcesoId" integer NOT NULL,
  "Tipo" varchar(20) NOT NULL,
  "Segmento" varchar(20),
  "CuentaOrigen" varchar(20),
  "CuentaDestino" varchar(20),
  "EstadoDestino" varchar(30),
  "BandaDestino" varchar(40),
  "Calificacion" varchar(5),
  "Operaciones" integer DEFAULT ((0)) NOT NULL,
  "Monto" numeric(15,2) NOT NULL
);

CREATE TABLE "dbo"."RegistroContable" (
  "AsientoId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "Fecha" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "SocioId" bigint,
  "CuentaContable" varchar(20) NOT NULL,
  "Concepto" varchar(200) NOT NULL,
  "Debe" numeric(18,2) DEFAULT ((0.00)) NOT NULL,
  "Haber" numeric(18,2) DEFAULT ((0.00)) NOT NULL,
  "NumeroCuenta" varchar(20) NOT NULL,
  "UsuarioId" varchar(50) NOT NULL
);

CREATE TABLE "dbo"."RegistroSocios" (
  "SOCIOID" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "TipoPersona" varchar(20) NOT NULL,
  "TipoIdentificacion" varchar(20) NOT NULL,
  "Identificacion" varchar(20) NOT NULL,
  "PrimerNombre" varchar(50) NOT NULL,
  "SegundoNombre" varchar(50),
  "Apellidos" varchar(100) NOT NULL,
  "Email" varchar(100),
  "Telefono" varchar(20),
  "FechaNacimiento" date,
  "EstadoCivil" varchar(20),
  "PIN" varchar(4) NOT NULL,
  "PaisNacimiento" varchar(50),
  "ProvinciaNacimiento" varchar(50),
  "CantonNacimiento" varchar(50),
  "ParroquiaNacimiento" varchar(50),
  "PaisResidencia" varchar(50),
  "ProvinciaResidencia" varchar(50),
  "CantonResidencia" varchar(50),
  "ParroquiaResidencia" varchar(50),
  "DireccionDomicilio" varchar(200),
  "LugarTrabajo" varchar(200),
  "ProvinciaTrabajo" varchar(50),
  "CantonTrabajo" varchar(50),
  "ParroquiaTrabajo" varchar(50),
  "CedulaConyuge" varchar(20),
  "NombreConyuge" varchar(150),
  "TelefonoConyuge" varchar(20),
  "Etnia" varchar(20),
  "Genero" varchar(20),
  "NivelInstruccion" varchar(50),
  "Profesion" varchar(100),
  "ReferenciasPersonales" text,
  "CargasFamiliares" text,
  "NumeroSocio" varchar(10),
  "FechaRegistro" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "UsuarioRegistro" varchar(50),
  "Estado" varchar(20) DEFAULT ('ACTIVO') NOT NULL,
  "PrimerApellido" varchar(50),
  "SegundoApellido" varchar(50),
  "SoloUnNombre" boolean DEFAULT false NOT NULL,
  "SoloUnApellido" boolean DEFAULT false NOT NULL,
  "EmailConfirmado" boolean DEFAULT false NOT NULL,
  "CodigoActivacion" varchar(10),
  "Telefonos" varchar(200),
  "Autoidentificacion" varchar(100),
  "TipoVivienda" varchar(100),
  "ValorVivienda" numeric(18,2),
  "Discapacidad" boolean DEFAULT false,
  "ConsentimientoDatos" boolean DEFAULT false,
  "PEPS" boolean DEFAULT false,
  "PatrimonioIngresos" text
);

CREATE TABLE "dbo"."RubrosCreditos" (
  "RubroID" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "AmortizacionID" integer NOT NULL,
  "NombreRubro" varchar(50) NOT NULL,
  "Monto" numeric(15,2) NOT NULL,
  "Estado" varchar(20) DEFAULT ('PENDIENTE') NOT NULL
);

CREATE TABLE "dbo"."SecuenciaDPF" (
  "Anio" integer NOT NULL,
  "Mes" integer NOT NULL,
  "UltimoN" integer DEFAULT ((0)) NOT NULL
);

CREATE TABLE "dbo"."SocioCroquisTrabajo" (
  "CroquisTrabajoID" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "SOCIOID" bigint NOT NULL,
  "ImagenCroquis" bytea,
  "Descripcion" varchar(500),
  "FechaCaptura" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "RutaImagen" varchar(250)
);

CREATE TABLE "dbo"."SocioDocumentoExcepcion" (
  "DocumentoID" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "SOCIOID" bigint NOT NULL,
  "Identificacion" varchar(20) NOT NULL,
  "RutaCaraFrontal" varchar(250),
  "RutaCaraPosterior" varchar(250),
  "FechaRegistro" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE "dbo"."SocioUbicacionMapa" (
  "UbicacionMapaID" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "SOCIOID" bigint NOT NULL,
  "ImagenMapa" bytea,
  "CoordenadaLat" varchar(50),
  "CoordenadaLng" varchar(50),
  "DireccionCapturada" varchar(200),
  "FechaCaptura" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "RutaImagen" varchar(250)
);

CREATE TABLE "dbo"."SolicitudesCredito" (
  "SolicitudID" varchar(50) NOT NULL,
  "SocioID" bigint,
  "Identificacion" varchar(20) NOT NULL,
  "Monto" numeric(15,2) NOT NULL,
  "Saldo" numeric(15,2) NOT NULL,
  "Tasa" numeric(5,2) NOT NULL,
  "Plazo" integer NOT NULL,
  "Tipo" varchar(100) NOT NULL,
  "Estado" varchar(20) NOT NULL,
  "FechaSolicitud" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "FechaVencimiento" varchar(50),
  "PlanPagos" text,
  "GarantiaInfo" text,
  "Origen" varchar(20),
  "TipoPrenda" varchar(100),
  "AvaluoPrendario" numeric(15,2),
  "ObservacionTecnicaPrenda" varchar(500),
  "ValorCobertura" numeric(10,2),
  "ScoringScore" integer,
  "DescuentosDesembolso" text,
  "TipoAprobacion" varchar(50),
  "ActaSesion" varchar(100),
  "Observaciones" varchar(500),
  "ICEPorcentaje" numeric(6,2),
  "ICEEstado" varchar(10),
  "ICECuotaMensual" numeric(15,2),
  "ICEIngresoNeto" numeric(15,2),
  "ICEDeudaExterna" numeric(15,2)
);

CREATE TABLE "dbo"."Stg_Clientes_Informix" (
  "clie_cod_clie" integer NOT NULL,
  "clie_cod_tcli" integer,
  "clie_num_clie" integer,
  "clie_cod_ofic" integer,
  "clie_cod_tide" char(1),
  "clie_ide_clie" char(13),
  "clie_ape_clie" char(60),
  "clie_nom_clie" char(30),
  "clie_fec_nac" date,
  "clie_cod_sect" integer,
  "clie_dir_domi" char(55),
  "clie_fec_uac" timestamp(0) without time zone,
  "clie_fec_ingr" timestamp(0) without time zone,
  "clie_fec_sali" date,
  "clie_ema_clie" char(80),
  "clie_nat_juri" smallint,
  "clie_est_clie" smallint,
  "clie_cal_clie" integer,
  "clie_rep_lega" varchar(50),
  "clie_ide_repr" char(13),
  "clie_tide_repr" char(1),
  "clie_cod_pais" integer,
  "clie_cod_usua" integer,
  "clie_cod_ofct" integer,
  "clie_ref_dire" char(100),
  "clie_cod_cocu" integer,
  "clie_est_adic" smallint,
  "clie_cod_disc" smallint,
  "clie_cod_tviv" integer,
  "clie_val_vivi" numeric(15,2),
  "clie_num_carg" smallint,
  "clie_cod_tcsr" integer,
  "clie_cod_auid" integer,
  "clie_fec_asan" date,
  "clie_cod_prof" integer,
  "clie_ban_peps" smallint,
  "clie_cod_tvin" integer,
  "clie_ban_grup" smallint,
  "clie_cod_grup" integer,
  "clie_cod_tres" integer,
  "clie_pai_resi" integer,
  "clie_ban_pdpe" smallint,
  "clie_hue_dact" char(10),
  "FechaCarga" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE "dbo"."Stg_Perfiles_Informix" (
  "perf_cod_perf" char(2) NOT NULL,
  "perf_des_perf" char(20) NOT NULL,
  "FechaCarga" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE "dbo"."Stg_Usuarios_Informix" (
  "usua_cod_usua" integer NOT NULL,
  "usua_cod_empl" integer NOT NULL,
  "usua_cod_perf" char(2) NOT NULL,
  "usua_nom_usua" char(25) NOT NULL,
  "usua_passwd" char(40),
  "usua_fec_uac" date,
  "usua_num_agen" integer,
  "usua_ban_usua" integer,
  "usua_imp_pred" char(100),
  "FechaCarga" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE "dbo"."TablaDeAmortizacion" (
  "AmortizacionID" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "CreditoID" varchar(50) NOT NULL,
  "NumeroCuota" integer NOT NULL,
  "FechaPago" varchar(50) NOT NULL,
  "Capital" numeric(15,2) NOT NULL,
  "Interes" numeric(15,2) NOT NULL,
  "SeguroDesgravamen" numeric(15,2) NOT NULL,
  "ContribucionSOLCA" numeric(15,2) NOT NULL,
  "GastosAdministrativos" numeric(15,2) NOT NULL,
  "Total" numeric(15,2) NOT NULL,
  "Estado" varchar(20) DEFAULT ('PENDIENTE') NOT NULL
);

CREATE TABLE "dbo"."TasasCredito" (
  "TasaId" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "LineaCredito" varchar(100) NOT NULL,
  "ClaseCredito" varchar(50) NOT NULL,
  "MontoMinimo" numeric(18,2) NOT NULL,
  "MontoMaximo" numeric(18,2) NOT NULL,
  "PlazoMinimo" integer NOT NULL,
  "PlazoMaximo" integer NOT NULL,
  "TasaInicial" numeric(5,2) NOT NULL,
  "TasaFinal" numeric(5,2) NOT NULL,
  "TasaAplicable" numeric(5,2) NOT NULL
);

CREATE TABLE "dbo"."TasasPlazoFijo" (
  "TasaID" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
  "CodigoRango" varchar(10) NOT NULL,
  "DescripcionRango" varchar(60) NOT NULL,
  "DiasDesde" integer NOT NULL,
  "DiasHasta" integer NOT NULL,
  "TasaNominalAnual" numeric(5,2) NOT NULL,
  "TasaMaximaBCE" numeric(5,2) NOT NULL,
  "MontoMinimo" numeric(15,2) DEFAULT ((200.00)) NOT NULL,
  "MontoMaximo" numeric(15,2),
  "CuentaContableDPF" varchar(10) NOT NULL,
  "PorcentajePenalizacion" numeric(5,2) DEFAULT ((50.00)) NOT NULL,
  "Activo" boolean DEFAULT true NOT NULL,
  "FechaVigencia" date DEFAULT CURRENT_DATE NOT NULL,
  "UsuarioConfigID" varchar(50)
);

CREATE TABLE "dbo"."Usuarios" (
  "UsuarioId" varchar(50) NOT NULL,
  "NombreCompleto" varchar(150) NOT NULL,
  "Pin" varchar(10),
  "Rol" varchar(30) NOT NULL,
  "Activo" boolean DEFAULT true NOT NULL,
  "PasswordHash" varchar(100),
  "RequiereCambioPin" boolean DEFAULT false NOT NULL,
  "FechaRegistro" date,
  "FechaCreacion" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "FechaActualizacion" timestamp(0) without time zone DEFAULT LOCALTIMESTAMP NOT NULL,
  "OrigenSistema" varchar(30),
  "OrigenUsuarioId" integer,
  "CodigoEmpleado" integer,
  "CodigoPerfil" varchar(10),
  "FechaUltimoAcceso" date,
  "NumeroAgencia" integer,
  "BanderaUsuario" integer,
  "ImpresoraPredeterminada" varchar(100),
  "Email" varchar(100),
  "Telefono" varchar(20),
  "Direccion" varchar(200),
  "ResetToken" varchar(200),
  "ResetTokenExpira" timestamp(6) without time zone,
  "PermisosModulos" text
);
CREATE INDEX "IX_ActivacionBancaLinea_SocioId" ON "dbo"."ActivacionBancaLinea" ("SocioId");
ALTER TABLE "dbo"."ActivacionBancaLinea" ADD CONSTRAINT "PK__Activaci__5FB13131BD898DD9" PRIMARY KEY ("ActivacionId");
ALTER TABLE "dbo"."AgenteEngrams" ADD CONSTRAINT "PK__AgenteEn__5A26459B69015B7A" PRIMARY KEY ("EngramId");
ALTER TABLE "dbo"."AgenteEngrams" ADD CONSTRAINT "UQ__AgenteEn__E8181E118ACA53A7" UNIQUE NULLS NOT DISTINCT ("Clave");
CREATE INDEX "IX_AsientosDPF_DepositoID" ON "dbo"."AsientosContablesDPF" ("DepositoID");
CREATE INDEX "IX_AsientosDPF_Fecha" ON "dbo"."AsientosContablesDPF" ("FechaAsiento");
ALTER TABLE "dbo"."AsientosContablesDPF" ADD CONSTRAINT "PK__Asientos__04904D30792C6EEC" PRIMARY KEY ("AsientoID");
CREATE INDEX "IX_AuditoriaProcesos_Entidad" ON "dbo"."AuditoriaProcesos" ("EntidadTipo", "EntidadId");
CREATE INDEX "IX_AuditoriaProcesos_Proceso_Fecha" ON "dbo"."AuditoriaProcesos" ("Proceso", "FechaRegistro" DESC);
ALTER TABLE "dbo"."AuditoriaProcesos" ADD CONSTRAINT "PK__Auditori__095694C3DA5F306E" PRIMARY KEY ("AuditoriaId");
ALTER TABLE "dbo"."AuditoriaUsuarios" ADD CONSTRAINT "PK__Auditori__095694C36AC47F61" PRIMARY KEY ("AuditoriaId");
ALTER TABLE "dbo"."ClientesInformix" ADD CONSTRAINT "PK__Clientes__92D416A533E708E6" PRIMARY KEY ("ClienteInformixId");
CREATE UNIQUE INDEX "UX_ClientesInformix_Origen" ON "dbo"."ClientesInformix" ("OrigenSistema", "OrigenClienteId") NULLS NOT DISTINCT;
ALTER TABLE "dbo"."ControlCaja" ADD CONSTRAINT "PK__ControlC__091D9B35FA503C73" PRIMARY KEY ("ControlId");
ALTER TABLE "dbo"."ControlCaja" ADD CONSTRAINT "UC_ControlCaja_Usuario_Fecha" UNIQUE NULLS NOT DISTINCT ("UsuarioId", "Fecha");
ALTER TABLE "dbo"."Creditos" ADD CONSTRAINT "PK__Creditos__4FE406FD312F67F6" PRIMARY KEY ("CreditoID");
ALTER TABLE "dbo"."CuentasAhorro" ADD CONSTRAINT "PK__CuentasA__40072E81EC96C488" PRIMARY KEY ("CuentaId");
ALTER TABLE "dbo"."CuentasAhorro" ADD CONSTRAINT "UQ__CuentasA__E039507BC37A31AB" UNIQUE NULLS NOT DISTINCT ("NumeroCuenta");
ALTER TABLE "dbo"."Denominaciones" ADD CONSTRAINT "PK__Denomina__5727C397FD7977E4" PRIMARY KEY ("CodigoDenominacion");
CREATE INDEX "IX_DepositosPlazo_Estado" ON "dbo"."DepositosPlazo" ("Estado");
CREATE INDEX "IX_DepositosPlazo_FechaVencimiento" ON "dbo"."DepositosPlazo" ("FechaVencimiento");
CREATE INDEX "IX_DepositosPlazo_SOCIOID" ON "dbo"."DepositosPlazo" ("SOCIOID");
ALTER TABLE "dbo"."DepositosPlazo" ADD CONSTRAINT "PK__Deposito__345C21B845CFCD55" PRIMARY KEY ("DepositoID");
ALTER TABLE "dbo"."DetalleEfectivoTransaccion" ADD CONSTRAINT "PK__DetalleE__6E19D6DA1AF8DBCF" PRIMARY KEY ("DetalleId");
ALTER TABLE "dbo"."HomologacionPerfilInformix" ADD CONSTRAINT "PK__Homologa__35B496DDC82C5BCC" PRIMARY KEY ("CodigoPerfil");
ALTER TABLE "dbo"."MigracionesAplicadas" ADD CONSTRAINT "PK__Migracio__62F0801C1C3A2694" PRIMARY KEY ("MigracionId");
CREATE UNIQUE INDEX "UX_Migr_Archivo" ON "dbo"."MigracionesAplicadas" ("Archivo") NULLS NOT DISTINCT;
ALTER TABLE "dbo"."ParametrosPatrimonioTecnico" ADD CONSTRAINT "PK__Parametr__2B3CE652E3C0707E" PRIMARY KEY ("ParametroId");
CREATE UNIQUE INDEX "UX_ParPT_Comp_Prefijo" ON "dbo"."ParametrosPatrimonioTecnico" ("Componente", "PrefijoCuenta") NULLS NOT DISTINCT;
ALTER TABLE "dbo"."parametrosproductos" ADD CONSTRAINT "PK__parametr__A430AEA3467F8AD0" PRIMARY KEY ("ProductoId");
ALTER TABLE "dbo"."parametrosproductos" ADD CONSTRAINT "UQ__parametr__785B009FEBC7B449" UNIQUE NULLS NOT DISTINCT ("CodigoProducto");
ALTER TABLE "dbo"."ParametrosProvisionCartera" ADD CONSTRAINT "PK__Parametr__2B3CE6525D6F5296" PRIMARY KEY ("ParametroId");
CREATE UNIQUE INDEX "UX_ParProv_Segmento_Calif" ON "dbo"."ParametrosProvisionCartera" ("Segmento", "Calificacion") NULLS NOT DISTINCT;
ALTER TABLE "dbo"."ParametrosRegulatorios" ADD CONSTRAINT "PK__Parametr__E8181E10BEC16800" PRIMARY KEY ("Clave");
ALTER TABLE "dbo"."PlanCuentas" ADD CONSTRAINT "PK__PlanCuen__4B19566B7469E48B" PRIMARY KEY ("CuentaContableId");
ALTER TABLE "dbo"."PlanCuentas" ADD CONSTRAINT "UQ_PlanCuentas_Codigo" UNIQUE NULLS NOT DISTINCT ("Codigo");
ALTER TABLE "dbo"."PonderacionesRiesgo" ADD CONSTRAINT "PK__Ponderac__E17BE778C16AC4F2" PRIMARY KEY ("PonderacionId");
CREATE UNIQUE INDEX "UX_PondRiesgo_Prefijo" ON "dbo"."PonderacionesRiesgo" ("PrefijoCuenta") NULLS NOT DISTINCT;
CREATE INDEX "IX_RecCart_Corte" ON "dbo"."ReclasificacionCartera" ("FechaCorte", "Estado");
ALTER TABLE "dbo"."ReclasificacionCartera" ADD CONSTRAINT "PK__Reclasif__1C00FFD04035039F" PRIMARY KEY ("ProcesoId");
CREATE UNIQUE INDEX "UX_RecCart_CorteAplicado" ON "dbo"."ReclasificacionCartera" ("FechaCorte") NULLS NOT DISTINCT WHERE ("Estado"='APLICADO');
CREATE INDEX "IX_RecCartDet_Proceso" ON "dbo"."ReclasificacionCarteraDetalle" ("ProcesoId", "Tipo");
ALTER TABLE "dbo"."ReclasificacionCarteraDetalle" ADD CONSTRAINT "PK__Reclasif__6E19D6DAC3166E4F" PRIMARY KEY ("DetalleId");
ALTER TABLE "dbo"."RegistroContable" ADD CONSTRAINT "PK__Registro__04904D104B0552CC" PRIMARY KEY ("AsientoId");
CREATE INDEX "IX_RegistroSocios_FechaRegistro" ON "dbo"."RegistroSocios" ("FechaRegistro");
CREATE INDEX "IX_RegistroSocios_TipoPersona" ON "dbo"."RegistroSocios" ("TipoPersona");
ALTER TABLE "dbo"."RegistroSocios" ADD CONSTRAINT "PK__Registro__77121E2FBE16DE5A" PRIMARY KEY ("SOCIOID");
ALTER TABLE "dbo"."RegistroSocios" ADD CONSTRAINT "UQ_RegistroSocios_Identificacion" UNIQUE NULLS NOT DISTINCT ("Identificacion");
ALTER TABLE "dbo"."RubrosCreditos" ADD CONSTRAINT "PK__RubrosCr__719694C087947403" PRIMARY KEY ("RubroID");
ALTER TABLE "dbo"."SecuenciaDPF" ADD CONSTRAINT "PK__Secuenci__19D296C18BFECA12" PRIMARY KEY ("Anio", "Mes");
ALTER TABLE "dbo"."SocioCroquisTrabajo" ADD CONSTRAINT "PK__SocioCro__2AE5BB723000A6E3" PRIMARY KEY ("CroquisTrabajoID");
ALTER TABLE "dbo"."SocioDocumentoExcepcion" ADD CONSTRAINT "PK__SocioDoc__5DDBFF96CAC048E7" PRIMARY KEY ("DocumentoID");
ALTER TABLE "dbo"."SocioUbicacionMapa" ADD CONSTRAINT "PK__SocioUbi__9338390642AE1BD7" PRIMARY KEY ("UbicacionMapaID");
ALTER TABLE "dbo"."SolicitudesCredito" ADD CONSTRAINT "PK__Solicitu__85E95DA7458C20F7" PRIMARY KEY ("SolicitudID");
CREATE INDEX "IX_Stg_Clientes_Informix_CodigoCliente" ON "dbo"."Stg_Clientes_Informix" ("clie_cod_clie");
CREATE INDEX "IX_Stg_Perfiles_Informix_CodigoPerfil" ON "dbo"."Stg_Perfiles_Informix" ("perf_cod_perf");
CREATE INDEX "IX_Stg_Usuarios_Informix_CodigoUsuario" ON "dbo"."Stg_Usuarios_Informix" ("usua_cod_usua");
ALTER TABLE "dbo"."TablaDeAmortizacion" ADD CONSTRAINT "PK__TablaDeA__6F0A95FD13DA00AB" PRIMARY KEY ("AmortizacionID");
ALTER TABLE "dbo"."TasasCredito" ADD CONSTRAINT "PK__TasasCre__7DED266D56B309D7" PRIMARY KEY ("TasaId");
ALTER TABLE "dbo"."TasasCredito" ADD CONSTRAINT "UQ__TasasCre__DFA01B74A8701BE4" UNIQUE NULLS NOT DISTINCT ("LineaCredito");
ALTER TABLE "dbo"."TasasPlazoFijo" ADD CONSTRAINT "PK__TasasPla__7DED260DB4C8101C" PRIMARY KEY ("TasaID");
ALTER TABLE "dbo"."Usuarios" ADD CONSTRAINT "PK__Usuarios__2B3DE7B8E4415D40" PRIMARY KEY ("UsuarioId");
CREATE UNIQUE INDEX "UX_Usuarios_OrigenInformix" ON "dbo"."Usuarios" ("OrigenSistema", "OrigenUsuarioId") NULLS NOT DISTINCT WHERE ("OrigenSistema" IS NOT NULL AND "OrigenUsuarioId" IS NOT NULL);
ALTER TABLE "dbo"."AsientosContablesDPF" ADD CONSTRAINT "CK_AsientosDPF_TipoOp" CHECK ("TipoOperacion"='RENOVACION' OR "TipoOperacion"='CANCELACION_ANTICIPADA' OR "TipoOperacion"='LIQUIDACION' OR "TipoOperacion"='APERTURA');
ALTER TABLE "dbo"."ControlCaja" ADD CONSTRAINT "CK__ControlCa__Estad__6E8B6712" CHECK ("Estado"='CERRADO' OR "Estado"='ABIERTO');
ALTER TABLE "dbo"."Denominaciones" ADD CONSTRAINT "CK__Denominaci__Tipo__5C6CB6D7" CHECK ("Tipo"='MONEDA' OR "Tipo"='BILLETE');
ALTER TABLE "dbo"."DepositosPlazo" ADD CONSTRAINT "CK_DPF_Estado" CHECK ("Estado"='RENOVADO' OR "Estado"='CANCELADO' OR "Estado"='LIQUIDADO' OR "Estado"='VENCIDO' OR "Estado"='ACTIVO');
ALTER TABLE "dbo"."DepositosPlazo" ADD CONSTRAINT "CK_DPF_Modalidad" CHECK ("ModalidadPago"='TRIMESTRAL' OR "ModalidadPago"='MENSUAL' OR "ModalidadPago"='AL_VENCIMIENTO');
ALTER TABLE "dbo"."DepositosPlazo" ADD CONSTRAINT "CK_DPF_Renovacion" CHECK ("TipoRenovacion"='MANUAL' OR "TipoRenovacion"='AUTOMATICO' OR "TipoRenovacion"='NO_RENOVAR');
ALTER TABLE "dbo"."ParametrosPatrimonioTecnico" ADD CONSTRAINT "CK_ParPT_Componente" CHECK ("Componente"='DEDUCCION' OR "Componente"='SECUNDARIO' OR "Componente"='PRIMARIO');
ALTER TABLE "dbo"."ParametrosPatrimonioTecnico" ADD CONSTRAINT "CK_ParPT_SaldoComo" CHECK ("SaldoComo"='DEUDOR' OR "SaldoComo"='ACREEDOR');
ALTER TABLE "dbo"."PlanCuentas" ADD CONSTRAINT "CK_PlanCuentas_Tipo" CHECK ("TipoCuenta"='ORDEN' OR "TipoCuenta"='CONTINGENTE' OR "TipoCuenta"='GASTO' OR "TipoCuenta"='INGRESO' OR "TipoCuenta"='PATRIMONIO' OR "TipoCuenta"='PASIVO' OR "TipoCuenta"='ACTIVO');
ALTER TABLE "dbo"."ReclasificacionCartera" ADD CONSTRAINT "CK_RecCart_Estado" CHECK ("Estado"='REVERSADO' OR "Estado"='APLICADO' OR "Estado"='SIMULADO');
ALTER TABLE "dbo"."SolicitudesCredito" ADD CONSTRAINT "CK_SolicitudesCredito_ICEEstado" CHECK ("ICEEstado" IS NULL OR ("ICEEstado"='BLOQUEADO' OR "ICEEstado"='ALERTA' OR "ICEEstado"='APROBADO'));
ALTER TABLE "dbo"."ActivacionBancaLinea" ADD CONSTRAINT "FK_ActivacionBancaLinea_RegistroSocios" FOREIGN KEY ("SocioId") REFERENCES "dbo"."RegistroSocios" ("SOCIOID") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "dbo"."AsientosContablesDPF" ADD CONSTRAINT "FK_AsientosDPF_DepositoID" FOREIGN KEY ("DepositoID") REFERENCES "dbo"."DepositosPlazo" ("DepositoID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Creditos" ADD CONSTRAINT "FK_Creditos_SocioID" FOREIGN KEY ("SocioID") REFERENCES "dbo"."RegistroSocios" ("SOCIOID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."Creditos" ADD CONSTRAINT "FK_Creditos_SolicitudID" FOREIGN KEY ("SolicitudID") REFERENCES "dbo"."SolicitudesCredito" ("SolicitudID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."CuentasAhorro" ADD CONSTRAINT "FK_CuentasAhorro_Parametros" FOREIGN KEY ("CodigoProducto") REFERENCES "dbo"."parametrosproductos" ("CodigoProducto") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."CuentasAhorro" ADD CONSTRAINT "FK_CuentasAhorro_RegistroSocios" FOREIGN KEY ("SocioId") REFERENCES "dbo"."RegistroSocios" ("SOCIOID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."DepositosPlazo" ADD CONSTRAINT "FK_DPF_SOCIOID" FOREIGN KEY ("SOCIOID") REFERENCES "dbo"."RegistroSocios" ("SOCIOID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."DepositosPlazo" ADD CONSTRAINT "FK_DPF_TasaID" FOREIGN KEY ("TasaID") REFERENCES "dbo"."TasasPlazoFijo" ("TasaID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."DetalleEfectivoTransaccion" ADD CONSTRAINT "FK_DetalleEfectivo_Denominaciones" FOREIGN KEY ("CodigoDenominacion") REFERENCES "dbo"."Denominaciones" ("CodigoDenominacion") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."DetalleEfectivoTransaccion" ADD CONSTRAINT "FK_DetalleEfectivo_RegistroContable" FOREIGN KEY ("AsientoId") REFERENCES "dbo"."RegistroContable" ("AsientoId") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "dbo"."ReclasificacionCarteraDetalle" ADD CONSTRAINT "FK_RecCartDet_Proceso" FOREIGN KEY ("ProcesoId") REFERENCES "dbo"."ReclasificacionCartera" ("ProcesoId") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."RegistroContable" ADD CONSTRAINT "FK_RegistroContable_Socio" FOREIGN KEY ("SocioId") REFERENCES "dbo"."RegistroSocios" ("SOCIOID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."RubrosCreditos" ADD CONSTRAINT "FK_RubrosCreditos_AmortizacionID" FOREIGN KEY ("AmortizacionID") REFERENCES "dbo"."TablaDeAmortizacion" ("AmortizacionID") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "dbo"."SocioCroquisTrabajo" ADD CONSTRAINT "FK_SocioCroquisTrabajo_SOCIOID" FOREIGN KEY ("SOCIOID") REFERENCES "dbo"."RegistroSocios" ("SOCIOID") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "dbo"."SocioDocumentoExcepcion" ADD CONSTRAINT "FK_SocioDocumentoExcepcion_SOCIOID" FOREIGN KEY ("SOCIOID") REFERENCES "dbo"."RegistroSocios" ("SOCIOID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."SocioUbicacionMapa" ADD CONSTRAINT "FK_SocioUbicacionMapa_SOCIOID" FOREIGN KEY ("SOCIOID") REFERENCES "dbo"."RegistroSocios" ("SOCIOID") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "dbo"."SolicitudesCredito" ADD CONSTRAINT "FK_SolicitudesCredito_RegistroSocios" FOREIGN KEY ("SocioID") REFERENCES "dbo"."RegistroSocios" ("SOCIOID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "dbo"."TablaDeAmortizacion" ADD CONSTRAINT "FK_TablaDeAmortizacion_CreditoID" FOREIGN KEY ("CreditoID") REFERENCES "dbo"."Creditos" ("CreditoID") ON DELETE CASCADE ON UPDATE NO ACTION;
