-- Extraccion base de clientes desde Informix AFC
-- Tabla origen: afccajapatate:bcaclie

SELECT
    clie_cod_clie,
    clie_cod_tcli,
    clie_num_clie,
    clie_cod_ofic,
    TRIM(clie_cod_tide) AS clie_cod_tide,
    TRIM(clie_ide_clie) AS clie_ide_clie,
    TRIM(clie_ape_clie) AS clie_ape_clie,
    TRIM(clie_nom_clie) AS clie_nom_clie,
    clie_fec_nac,
    clie_cod_sect,
    TRIM(clie_dir_domi) AS clie_dir_domi,
    clie_fec_uac,
    clie_fec_ingr,
    clie_fec_sali,
    TRIM(clie_ema_clie) AS clie_ema_clie,
    clie_nat_juri,
    clie_est_clie,
    clie_cal_clie,
    TRIM(clie_rep_lega) AS clie_rep_lega,
    TRIM(clie_ide_repr) AS clie_ide_repr,
    TRIM(clie_tide_repr) AS clie_tide_repr,
    clie_cod_pais,
    clie_cod_usua,
    clie_cod_ofct,
    TRIM(clie_ref_dire) AS clie_ref_dire,
    clie_cod_cocu,
    clie_est_adic,
    clie_cod_disc,
    clie_cod_tviv,
    clie_val_vivi,
    clie_num_carg,
    clie_cod_tcsr,
    clie_cod_auid,
    clie_fec_asan,
    clie_cod_prof,
    clie_ban_peps,
    clie_cod_tvin,
    clie_ban_grup,
    clie_cod_grup,
    clie_cod_tres,
    clie_pai_resi,
    clie_ban_pdpe,
    TRIM(clie_hue_dact) AS clie_hue_dact
FROM afccajapatate:bcaclie
ORDER BY clie_cod_clie;
